source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target 'Hybird_ReactNative' do

pod "React"
pod "React/RCTText"
pod "React/RCTActionSheet"
pod "React/RCTGeolocation"
pod "React/RCTImage"
pod "React/RCTLinkingIOS"
pod "React/RCTNetwork"
pod "React/RCTSettings"
pod "React/RCTVibration"
pod "React/RCTWebSocket"
pod "React/RCTAnimationExperimental"

end
